project:
  type: website

website:
  title: "Jason Saito's Website"
  navbar:
    right:
      - text: Projects
          menu: 
            - text: Project 1
              href: project.qmd  
            - text: Project 2
              href: project.qmd
            - text: Project 3
              href: project.qmd
      - interests.qmd
      - blog.qmd
      - icon: github
        href: https://github.com/jason-saito
      - icon: linkedin
        href: https://www.linkedin.com/in/jason-saito/
format:
  html:
    theme: morph
    css: styles.css

execute:
  freeze: auto