project:
  type: website

website:
  title: "Jason Saito's Website"
  navbar:
    right:
      - blog.qmd
      - about.qmd
      - projects.qmd
      - interests.qmd
      - icon: github
        href: https://github.com/jason-saito
      - icon: linkedin
        href: https://www.linkedin.com/in/jason-saito/
format:
  html:
    theme: morph
    css: styles.css

execute:
  freeze: auto


