project:
  type: website

website:
  title: "Jason Saito's Website"
  navbar:
    right:
      - projects.qmd
      - text: Interests
        menu:
          - text: LLMs Blog
            href: blog.qmd  
          - text: Project 2
            href: blog.qmd  
          - text: Project 3
            href: blog.qmd
      - icon: github
        href: https://github.com/jason-saito
      - icon: linkedin
        href: https://www.linkedin.com/in/jason-saito/
      - icon: gmail
        href: mailto:jsaito@sas.upenn.edu
format:
  html:
    theme: morph
    css: styles.css

execute:
  freeze: auto
